---
name: Setup SSH
description: Setup the SSH agent and known hosts
branding:
  icon: command
  color: white

inputs:
  host:
    description: Hostname of the SSH server. Multiple hosts can be provided as a multiline string.
    required: false
  private-key:
    description: PEM-encoded SSH private key for pulling the Shipyard registry index. Multiple keys can be provided as a multiline string.
    required: true

runs:
  using: composite
  steps:
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.private-key }}

    - name: Ensure .ssh/known_hosts exists
      shell: bash
      if: inputs.host
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts

    - name: Add host key(s) to .ssh/known_hosts
      shell: bash
      if: inputs.host
      run: |
        IFS=$'\n' hosts=(${{ inputs.host }})
        for host in "${hosts[@]}"; do
          ssh-keyscan $host >> ~/.ssh/known_hosts
        done
